server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${mongodb+srv://ri:Hcp0UK6fVTjKKXob@k8s.aquj9hz.mongodb.net/myDB?retryWrites=true&w=majority&appName=k8s}
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}
  expiration: 86400000 # 24 hours

logging:
  level:
    in.cloudblitz.auth: DEBUG
