server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://ri:Hcp0UK6fVTjKKXob@k8s.aquj9hz.mongodb.net/myDB?retryWrites=true&w=majority&appName=k8s
logging:
  level:
    in.cloudblitz.course: DEBUG
